database:
  host: localhost
  port: 5432
  user: dummy_user
  password: dummy_password
  db: dummy_db

server:
  port: 1337
  allowed_origins:
    - http://localhost:5173

localization:
    default_locale: en
    supported_locales:
      - de